services:
  frontend:
    image: node:alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./Frontend/Web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - mongo_network
    command: sh -c "npm install && npm run dev -- --host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 10s
      timeout: 5s
      retries: 3

  api_gateway:
    image: node:alpine
    container_name: api_gateway
    working_dir: /app
    restart: always
    volumes:
      - ./Backend/api_gateway:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - mongo_network
    command: sh -c "npm install && npm run start:dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  chantier_service:
    image: node:alpine
    container_name: chantier_service
    working_dir: /app
    restart: on-failure:5
    volumes:
      - ./Backend/chantier_service:/app
      - /app/node_modules
    ports:
      - 4444:4444
    networks:
      - mongo_network
    environment:
      MONGO_URL: "mongodb://admin:secret@mongo_db:27017/btp_module_db?authSource=admin"
      REDIS_URL: "redis://redis:6379"
    command: sh -c "npm install && npm run start:dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/chantiers"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  devis_service:
    image: node:alpine
    container_name: devis_service
    working_dir: /app
    restart: on-failure:5
    volumes:
      - ./Backend/devis_service:/app
      - /app/node_modules
    ports:
      - 4445:4445
    networks:
      - mongo_network
    environment:
      MONGO_URL: "mongodb://admin:secret@mongo_db:27017/btp_module_db?authSource=admin"
      REDIS_URL: "redis://redis:6379"
    command: sh -c "npm install && npm run start:dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/devis"]
      interval: 10s
      timeout: 5s
      retries: 3

  multi_service:
    image: node:alpine
    container_name: multi_service
    working_dir: /app
    volumes:
      - ./Backend/multi_service:/app
      - /app/node_modules
    ports:
      - 4446:4446
    networks:
      - mongo_network
    restart: on-failure:5
    environment:
      MONGO_URL: "mongodb://admin:secret@mongo_db:27017/btp_module_db?authSource=admin"
      REDIS_URL: "redis://redis:6379"
    command: sh -c "npm install && npm run start:dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/multi"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mongo_network
    volumes:
      - mongo_data:/data/db
      #- ./database/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    command: ["mongod", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongo_seed:
    image: node:alpine
    container_name: mongo_seed
    depends_on:
      mongo_db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./Database:/app
    command: sh -c "npm install mongoose && node init.js"
    networks:
      - mongo_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mongo_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: "default" 
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: "mongodb://admin:secret@mongo_db:27017/btp_module_db?authSource=admin"
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  mongo_network:
    driver: bridge
    attachable: true



volumes:
  mongo_data:
  redis_data:
  
