const mongoose = require('mongoose');
const { Schema } = mongoose;

// Gestion des événements MongoDB
mongoose.connection.on('connected', () => {
  console.log('Connexion à MongoDB réussie');
});

mongoose.connection.on('error', (err) => {
  console.error('Erreur de connexion à MongoDB :', err);
});

mongoose.connection.on('disconnected', () => {
  console.log('Déconnecté de MongoDB');
});

// Connexion à MongoDB
mongoose.connect('mongodb://admin:secret@mongo_db:27017/btp_module_db', {
  authSource: 'admin',
  connectTimeoutMS: 30000,
});

// Schémas des collections
const chantierSchema = new Schema({
  numero: String,
  title: String,
  description: String,
  notes: [String],
  commentaires: [String],
  client: String,
  status: String,
  debut_prevu: Date,
  fin_prevu: Date,
  personnels: [{ type: Schema.Types.ObjectId, ref: 'Personnel' }],
  fournitures: [{ type: Schema.Types.ObjectId, ref: 'Fourniture' }],
  outillages: [{ type: Schema.Types.ObjectId, ref: 'Outils' }],
  devis: [{ type: Schema.Types.ObjectId, ref: 'Devis' }],
  adresse: String,
  code_postal: String,
  ville: String,
  localisation: { lon: Number, lat: Number },
});

const devisSchema = new Schema({
  numero: String,
  title: String,
  description: String,
  notes: String,
  client: String,
  status: String,
  debut_prevu: Date,
  fin_prevu: Date,
  date_echeance: Date,
  mode_reglement: String,
  tva: String,
  devis_lines: [String],
});

const fournitureSchema = new Schema({
  name: String,
  description: String,
  unit: String,
  quantity: Number,
  total_price: Number,
});

const outilsSchema = new Schema({
  name: String,
  type: String,
  available: Boolean,
  quantity: Number,
  quantity_available: Number,
});

const personnelSchema = new Schema({
  name: String,
  role: String,
  active: Boolean,
  phone: String,
  email: String,
});

// Création des modèles
const Chantier = mongoose.model('Chantier', chantierSchema);
const Devis = mongoose.model('Devis', devisSchema);
const Fourniture = mongoose.model('Fourniture', fournitureSchema);
const Outils = mongoose.model('Outils', outilsSchema);
const Personnel = mongoose.model('Personnel', personnelSchema);

// Fonction de seed
async function seedDatabase() {
  try {
    const chantierCount = await Chantier.countDocuments();
    if (chantierCount > 0) {
      console.log('La base de données est déjà peuplée. Aucun seed nécessaire.');
      return;
    }

    // Suppression des données existantes
    await Chantier.deleteMany();
    await Devis.deleteMany();
    await Fourniture.deleteMany();
    await Outils.deleteMany();
    await Personnel.deleteMany();

    // Création des données de seed
    const personnels = await Personnel.insertMany([
      { name: 'Jean Dupont', role: 'Carreleur', active: true, phone: '0601234567', email: 'jean.dupont@mail.com' },
      { name: 'Marie Curie', role: 'Chef de chantier', active: true, phone: '0612345678', email: 'marie.curie@mail.com' },
      { name: 'Paul Martin', role: 'Chapiste', active: true, phone: '0623456789', email: 'paul.martin@mail.com' },
      { name: 'Lucie Bernard', role: 'Assistante', active: true, phone: '0634567890', email: 'lucie.bernard@mail.com' },
      { name: 'Marc Leclerc', role: 'Carreleur', active: true, phone: '0645678901', email: 'marc.leclerc@mail.com' },
      { name: 'Sophie Garnier', role: 'Chapiste', active: true, phone: '0656789012', email: 'sophie.garnier@mail.com' },
      { name: 'Antoine Dubois', role: 'Ouvrier polyvalent', active: true, phone: '0667890123', email: 'antoine.dubois@mail.com' },
      { name: 'Emma Robert', role: 'TechniChapistecienne', active: true, phone: '0678901234', email: 'emma.robert@mail.com' },
      { name: 'Lucas Moreau', role: 'Conducteur d’engins', active: true, phone: '0689012345', email: 'lucas.moreau@mail.com' },
      { name: 'Clara Petit', role: 'Gestionnaire', active: true, phone: '0690123456', email: 'clara.petit@mail.com' },
    ]);

    const outils = await Outils.insertMany([
      { name: 'Marteau', type: 'Outil de base', available: true, quantity: 10, quantity_available: 10 },
      { name: 'Truelle', type: 'Outil de finition', available: true, quantity: 5, quantity_available: 5 },
      { name: 'Niveau à bulle', type: 'Outil de mesure', available: true, quantity: 5, quantity_available: 5 },
      { name: 'Scie circulaire', type: 'Outil électrique', available: true, quantity: 3, quantity_available: 3 },
      { name: 'Perceuse', type: 'Outil électrique', available: true, quantity: 4, quantity_available: 4 },
      { name: 'Visseuse', type: 'Outil électrique', available: true, quantity: 6, quantity_available: 6 },
      { name: 'Pelle', type: 'Outil de chantier', available: true, quantity: 8, quantity_available: 8 },
      { name: 'Brouette', type: 'Outil de transport', available: true, quantity: 4, quantity_available: 4 },
      { name: 'Cutter', type: 'Outil de coupe', available: true, quantity: 7, quantity_available: 7 },
      { name: 'Laser de mesure', type: 'Outil de mesure', available: true, quantity: 2, quantity_available: 2 },
    ]);

    const fournitures = await Fourniture.insertMany([
      { name: 'Carrelage 30x30', description: 'Carrelage blanc pour salle de bain', unit: 'm²', quantity: 50, total_price: 525 },
      { name: 'Parquet chêne massif', description: 'Parquet haut de gamme', unit: 'm²', quantity: 20, total_price: 700 },
      { name: 'Ciment rapide', description: 'Ciment à prise rapide pour chape', unit: 'kg', quantity: 100, total_price: 800 },
      { name: 'Adhésif de carrelage', description: 'Colle pour carrelage', unit: 'kg', quantity: 50, total_price: 750 },
      { name: 'Joint silicone', description: 'Joint pour étanchéité', unit: 'tube', quantity: 30, total_price: 150 },
      { name: 'Plinthe en bois', description: 'Plinthe assortie au parquet', unit: 'm', quantity: 100, total_price: 1200 },
      { name: 'Peinture murale blanche', description: 'Peinture acrylique', unit: 'L', quantity: 20, total_price: 500 },
      { name: 'Carrelage imitation bois', description: 'Carrelage effet parquet', unit: 'm²', quantity: 40, total_price: 720 },
      { name: 'Produit de nettoyage', description: 'Nettoyant pour carrelage', unit: 'L', quantity: 30, total_price: 240 },
      { name: 'Film polyane', description: 'Film étanche pour chape', unit: 'm²', quantity: 100, total_price: 300 },
    ]);

    const devis = await Devis.insertMany([
      {
        numero: 'DV-001',
        title: 'Devis rénovation salle de bain',
        description: 'Pose de carrelage et finition',
        notes: 'Inclure les finitions murales',
        client: 'Jean Dupont',
        status: 'En attente',
        debut_prevu: new Date('2024-12-01'),
        fin_prevu: new Date('2024-12-15'),
        date_echeance: new Date('2024-12-20'),
        mode_reglement: 'Chèque',
        tva: '20%',
        devis_lines: ['Carrelage 30x30', 'Pose complète'],
      },
    ]);

    await Chantier.insertMany([
  // 10 chantiers Terminé
  {
    numero: 'CH-101',
    title: 'Réhabilitation cuisine Martin',
    description: 'Pose de carrelage mural et sol',
    notes: 'Carrelage antidérapant recommandé',
    commentaires: 'Réalisé en octobre 2024',
    client: 'Paul Martin',
    status: 'Terminé',
    debut_prevu: new Date('2024-10-01'),
    fin_prevu: new Date('2024-10-15'),
    personnels: [personnels[0]._id, personnels[1]._id],
    fournitures: [fournitures[0]._id, fournitures[7]._id],
    outillages: [outils[0]._id, outils[3]._id],
    devis: [],
    adresse: '10 Rue de l’Industrie',
    code_postal: '75010',
    ville: 'Paris',
    localisation: { lon: 2.350987, lat: 48.873791 },
  },
  {
    numero: 'CH-102',
    title: 'Rénovation salle de bain Lefevre',
    description: 'Installation de carrelage et nouvelles sanitaires',
    notes: 'Pensez à vérifier l’étanchéité',
    commentaires: 'Clôturé en novembre 2024',
    client: 'Sophie Lefevre',
    status: 'Terminé',
    debut_prevu: new Date('2024-09-15'),
    fin_prevu: new Date('2024-10-01'),
    personnels: [personnels[2]._id, personnels[3]._id],
    fournitures: [fournitures[0]._id, fournitures[4]._id],
    outillages: [outils[1]._id, outils[2]._id],
    devis: [],
    adresse: '22 Avenue de la République',
    code_postal: '75011',
    ville: 'Paris',
    localisation: { lon: 2.369, lat: 48.860 },
  },
  {
    numero: 'CH-103',
    title: 'Pose de parquet Dubois',
    description: 'Installation de parquet chêne massif',
    notes: 'Vérifier la planéité du sol',
    commentaires: 'Terminé fin août 2024',
    client: 'Antoine Dubois',
    status: 'Terminé',
    debut_prevu: new Date('2024-08-01'),
    fin_prevu: new Date('2024-08-20'),
    personnels: [personnels[4]._id, personnels[5]._id],
    fournitures: [fournitures[1]._id],
    outillages: [outils[3]._id, outils[4]._id],
    devis: [],
    adresse: '5 Rue des Lilas',
    code_postal: '69001',
    ville: 'Lyon',
    localisation: { lon: 4.8357, lat: 45.7640 },
  },
  {
    numero: 'CH-104',
    title: 'Réfection de terrasse Moreau',
    description: 'Nettoyage, réparation et pose de carrelage extérieur',
    notes: 'Prévoir un traitement hydrofuge',
    commentaires: 'Finalisé en septembre 2024',
    client: 'Lucas Moreau',
    status: 'Terminé',
    debut_prevu: new Date('2024-09-01'),
    fin_prevu: new Date('2024-09-15'),
    personnels: [personnels[6]._id, personnels[7]._id],
    fournitures: [fournitures[7]._id, fournitures[9]._id],
    outillages: [outils[5]._id, outils[8]._id],
    devis: [],
    adresse: '78 Rue de Provence',
    code_postal: '13001',
    ville: 'Marseille',
    localisation: { lon: 5.3698, lat: 43.2965 },
  },
  {
    numero: 'CH-105',
    title: 'Aménagement bureau Renault',
    description: 'Pose de carrelage et isolation acoustique',
    notes: 'Utiliser carrelage spécifique pour bureaux',
    commentaires: 'Projet clôturé en octobre 2024',
    client: 'Alain Renault',
    status: 'Terminé',
    debut_prevu: new Date('2024-09-10'),
    fin_prevu: new Date('2024-09-25'),
    personnels: [personnels[0]._id, personnels[2]._id],
    fournitures: [fournitures[2]._id, fournitures[6]._id],
    outillages: [outils[2]._id, outils[6]._id],
    devis: [],
    adresse: '15 Rue Victor Hugo',
    code_postal: '75002',
    ville: 'Paris',
    localisation: { lon: 2.3364, lat: 48.8609 },
  },
  {
    numero: 'CH-106',
    title: 'Modernisation façade Petit',
    description: 'Rejointoiement et nettoyage extérieur',
    notes: 'Vérifier les anciens joints avant travaux',
    commentaires: 'Livré en juillet 2024',
    client: 'Clara Petit',
    status: 'Terminé',
    debut_prevu: new Date('2024-07-01'),
    fin_prevu: new Date('2024-07-10'),
    personnels: [personnels[8]._id],
    fournitures: [fournitures[4]._id],
    outillages: [outils[7]._id],
    devis: [],
    adresse: '33 Rue de la République',
    code_postal: '69002',
    ville: 'Lyon',
    localisation: { lon: 4.837, lat: 45.763 },
  },
  {
    numero: 'CH-107',
    title: 'Réfection sol d\'entrée Bernard',
    description: 'Pose de carrelage pour entrée',
    notes: 'Assurer une bonne adhérence',
    commentaires: 'Projet terminé en août 2024',
    client: 'Lucie Bernard',
    status: 'Terminé',
    debut_prevu: new Date('2024-08-05'),
    fin_prevu: new Date('2024-08-18'),
    personnels: [personnels[3]._id, personnels[7]._id],
    fournitures: [fournitures[0]._id, fournitures[5]._id],
    outillages: [outils[1]._id, outils[9]._id],
    devis: [],
    adresse: '19 Avenue Gambetta',
    code_postal: '75003',
    ville: 'Paris',
    localisation: { lon: 2.3522, lat: 48.8566 },
  },
  {
    numero: 'CH-108',
    title: 'Remise à neuf salle de réunion',
    description: 'Installation de carrelage moderne et éclairage LED',
    notes: 'Planifier une coordination avec l\'électricien',
    commentaires: 'Terminé début octobre 2024',
    client: 'Entreprise X',
    status: 'Terminé',
    debut_prevu: new Date('2024-09-20'),
    fin_prevu: new Date('2024-10-05'),
    personnels: [personnels[1]._id, personnels[4]._id],
    fournitures: [fournitures[1]._id, fournitures[2]._id],
    outillages: [outils[0]._id, outils[4]._id],
    devis: [],
    adresse: '66 Boulevard Saint-Germain',
    code_postal: '75006',
    ville: 'Paris',
    localisation: { lon: 2.333, lat: 48.854 },
  },
  {
    numero: 'CH-109',
    title: 'Rénovation local commercial',
    description: 'Installation de carrelage et menuiserie',
    notes: 'Respecter les normes ERP',
    commentaires: 'Conclu en septembre 2024',
    client: 'Société Commerciale',
    status: 'Terminé',
    debut_prevu: new Date('2024-08-15'),
    fin_prevu: new Date('2024-09-01'),
    personnels: [personnels[5]._id, personnels[9]._id],
    fournitures: [fournitures[3]._id, fournitures[8]._id],
    outillages: [outils[6]._id, outils[8]._id],
    devis: [],
    adresse: '90 Rue de Rivoli',
    code_postal: '75004',
    ville: 'Paris',
    localisation: { lon: 2.342, lat: 48.856 },
  },
  {
    numero: 'CH-110',
    title: 'Revêtement sol hôtel',
    description: 'Pose de carrelage haut de gamme dans halls et chambres',
    notes: 'Vérifier la livraison des matériaux',
    commentaires: 'Achevé en octobre 2024',
    client: 'Hôtel Belle Vue',
    status: 'Terminé',
    debut_prevu: new Date('2024-09-05'),
    fin_prevu: new Date('2024-09-20'),
    personnels: [personnels[0]._id, personnels[8]._id],
    fournitures: [fournitures[1]._id, fournitures[9]._id],
    outillages: [outils[2]._id, outils[5]._id],
    devis: [],
    adresse: '120 Rue de la Paix',
    code_postal: '75002',
    ville: 'Paris',
    localisation: { lon: 2.330, lat: 48.868 },
  },

  // 10 chantiers En cours
  {
    numero: 'CH-201',
    title: 'Modernisation façade Moderne',
    description: 'Rénovation et pose de carrelage extérieur',
    notes: 'Surveiller l’état de la façade',
    commentaires: 'En cours depuis début novembre 2024',
    client: 'Entreprise Moderne',
    status: 'En cours',
    debut_prevu: new Date('2024-11-01'),
    fin_prevu: new Date('2024-11-20'),
    personnels: [personnels[2]._id, personnels[6]._id],
    fournitures: [fournitures[0]._id, fournitures[2]._id],
    outillages: [outils[3]._id, outils[7]._id],
    devis: [],
    adresse: '8 Rue des Entrepreneurs',
    code_postal: '75012',
    ville: 'Paris',
    localisation: { lon: 2.362, lat: 48.856 },
  },
  {
    numero: 'CH-202',
    title: 'Rénovation vestibule Dupont',
    description: 'Pose de carrelage et rénovation du sol',
    notes: 'Penser à vérifier l\'étanchéité',
    commentaires: 'Travaux en cours',
    client: 'Jean Dupont',
    status: 'En cours',
    debut_prevu: new Date('2024-11-05'),
    fin_prevu: new Date('2024-11-25'),
    personnels: [personnels[0]._id, personnels[7]._id],
    fournitures: [fournitures[0]._id, fournitures[4]._id],
    outillages: [outils[1]._id, outils[2]._id],
    devis: [],
    adresse: '14 Rue de la Gare',
    code_postal: '75013',
    ville: 'Paris',
    localisation: { lon: 2.347, lat: 48.857 },
  },
  {
    numero: 'CH-203',
    title: 'Réaménagement studio Curie',
    description: 'Mise à jour du carrelage et peinture',
    notes: 'Coordination avec le client nécessaire',
    commentaires: 'Débuté le 10 novembre 2024',
    client: 'Marie Curie',
    status: 'En cours',
    debut_prevu: new Date('2024-11-10'),
    fin_prevu: new Date('2024-11-30'),
    personnels: [personnels[1]._id, personnels[3]._id],
    fournitures: [fournitures[1]._id, fournitures[7]._id],
    outillages: [outils[4]._id, outils[0]._id],
    devis: [],
    adresse: '26 Rue de la Liberté',
    code_postal: '75014',
    ville: 'Paris',
    localisation: { lon: 2.354, lat: 48.853 },
  },
  {
    numero: 'CH-204',
    title: 'Modernisation entrée de bureau',
    description: 'Pose de carrelage moderne avec éclairage',
    notes: 'Mise en place en deux temps',
    commentaires: 'En cours, prévision fin novembre 2024',
    client: 'Entreprise Y',
    status: 'En cours',
    debut_prevu: new Date('2024-11-12'),
    fin_prevu: new Date('2024-11-28'),
    personnels: [personnels[4]._id, personnels[9]._id],
    fournitures: [fournitures[2]._id, fournitures[5]._id],
    outillages: [outils[2]._id, outils[6]._id],
    devis: [],
    adresse: '55 Rue Lafayette',
    code_postal: '75009',
    ville: 'Paris',
    localisation: { lon: 2.331, lat: 48.877 },
  },
  {
    numero: 'CH-205',
    title: 'Rénovation local commercial Petit',
    description: 'Remplacement du carrelage et modernisation',
    notes: 'Suivre les instructions du client',
    commentaires: 'Travaux en cours',
    client: 'Clara Petit',
    status: 'En cours',
    debut_prevu: new Date('2024-11-15'),
    fin_prevu: new Date('2024-12-05'),
    personnels: [personnels[8]._id, personnels[2]._id],
    fournitures: [fournitures[3]._id, fournitures[9]._id],
    outillages: [outils[5]._id, outils[7]._id],
    devis: [],
    adresse: '32 Boulevard des Capucines',
    code_postal: '75002',
    ville: 'Paris',
    localisation: { lon: 2.345, lat: 48.860 },
  },
  {
    numero: 'CH-206',
    title: 'Mise à jour salle d\'exposition',
    description: 'Remplacement du carrelage ancien',
    notes: 'Inspecter le sous-plancher',
    commentaires: 'Débuté mi-novembre 2024',
    client: 'Galerie Moderne',
    status: 'En cours',
    debut_prevu: new Date('2024-11-18'),
    fin_prevu: new Date('2024-12-08'),
    personnels: [personnels[7]._id, personnels[6]._id],
    fournitures: [fournitures[0]._id, fournitures[6]._id],
    outillages: [outils[0]._id, outils[9]._id],
    devis: [],
    adresse: '101 Rue de Vaugirard',
    code_postal: '75015',
    ville: 'Paris',
    localisation: { lon: 2.352, lat: 48.833 },
  },
  {
    numero: 'CH-207',
    title: 'Réfection hall d\'accueil',
    description: 'Installation de carrelage résistant aux passages',
    notes: 'Validation des matériaux obligatoire',
    commentaires: 'En cours, prévision fin novembre 2024',
    client: 'Centre Commercial Z',
    status: 'En cours',
    debut_prevu: new Date('2024-11-20'),
    fin_prevu: new Date('2024-12-10'),
    personnels: [personnels[3]._id, personnels[5]._id],
    fournitures: [fournitures[4]._id, fournitures[8]._id],
    outillages: [outils[1]._id, outils[6]._id],
    devis: [],
    adresse: '77 Route de la Gare',
    code_postal: '75016',
    ville: 'Paris',
    localisation: { lon: 2.360, lat: 48.854 },
  },
  {
    numero: 'CH-208',
    title: 'Réhabilitation entrée centrale',
    description: 'Mise à jour complète du revêtement de sol',
    notes: 'Coordonner avec les autres corps de métier',
    commentaires: 'En cours, prévu fin novembre 2024',
    client: 'Mairie de Ville',
    status: 'En cours',
    debut_prevu: new Date('2024-11-22'),
    fin_prevu: new Date('2024-12-12'),
    personnels: [personnels[0]._id, personnels[8]._id],
    fournitures: [fournitures[1]._id, fournitures[7]._id],
    outillages: [outils[2]._id, outils[4]._id],
    devis: [],
    adresse: '88 Place de la Mairie',
    code_postal: '75017',
    ville: 'Paris',
    localisation: { lon: 2.345, lat: 48.859 },
  },
  {
    numero: 'CH-209',
    title: 'Rénovation escalier intérieur',
    description: 'Pose de carrelage sur marches et paliers',
    notes: 'Assurer une bonne adhérence sur les marches',
    commentaires: 'Démarrage prévu le 25 novembre 2024',
    client: 'Habitat Moderne',
    status: 'En cours',
    debut_prevu: new Date('2024-11-25'),
    fin_prevu: new Date('2024-12-15'),
    personnels: [personnels[2]._id, personnels[4]._id],
    fournitures: [fournitures[2]._id, fournitures[5]._id],
    outillages: [outils[1]._id, outils[7]._id],
    devis: [],
    adresse: '3 Rue des Escaliers',
    code_postal: '75018',
    ville: 'Paris',
    localisation: { lon: 2.350, lat: 48.861 },
  },
  {
    numero: 'CH-210',
    title: 'Modernisation sol d\'entrée',
    description: 'Réfection du revêtement de sol de l\'entrée principale',
    notes: 'Vérifier la résistance aux passages intensifs',
    commentaires: 'En cours depuis fin novembre 2024',
    client: 'Bureau Central',
    status: 'En cours',
    debut_prevu: new Date('2024-11-28'),
    fin_prevu: new Date('2024-12-18'),
    personnels: [personnels[1]._id, personnels[5]._id],
    fournitures: [fournitures[3]._id, fournitures[9]._id],
    outillages: [outils[0]._id, outils[8]._id],
    devis: [],
    adresse: '47 Boulevard Central',
    code_postal: '75019',
    ville: 'Paris',
    localisation: { lon: 2.361, lat: 48.864 },
  },

  // 1 chantier à voir
  {
    numero: 'CH-301',
    title: 'Étude préalable pour projet inconnu',
    description: 'Analyse et étude de faisabilité pour un futur chantier',
    notes: 'Projet à évaluer avant décision',
    commentaires: 'Statut à voir',
    client: 'Client Potentiel',
    status: 'À venir',
    debut_prevu: new Date('2024-12-01'),
    fin_prevu: new Date('2024-12-31'),
    personnels: [personnels[7]._id],
    fournitures: [fournitures[0]._id],
    outillages: [outils[2]._id],
    devis: [],
    adresse: '100 Rue des Perspectives',
    code_postal: '75020',
    ville: 'Paris',
    localisation: { lon: 2.360, lat: 48.860 },
  }
]);

await Chantier.insertMany([
  {
    numero: 'CH-401',
    title: 'Préparation espace détente',
    description: 'Étude et préparation du sol pour aménagement d\'un espace détente',
    notes: 'Vérifier l\'état du sol avant de commencer',
    commentaires: 'Projet prévu pour début 2025',
    client: 'Société Bien-Être',
    status: 'À venir',
    debut_prevu: new Date('2025-01-10'),
    fin_prevu: new Date('2025-01-25'),
    personnels: [personnels[1]._id, personnels[4]._id],
    fournitures: [fournitures[0]._id, fournitures[3]._id],
    outillages: [outils[2]._id, outils[5]._id],
    devis: [],
    adresse: '12 Rue des Jardins',
    code_postal: '75015',
    ville: 'Paris',
    localisation: { lon: 2.341, lat: 48.834 },
  },
  {
    numero: 'CH-402',
    title: 'Installation nouveaux revêtements',
    description: 'Pose d’un nouveau carrelage dans le hall d’entrée',
    notes: 'Choisir des matériaux résistants',
    commentaires: 'Planning à confirmer pour février 2025',
    client: 'Immeuble Central',
    status: 'À venir',
    debut_prevu: new Date('2025-02-05'),
    fin_prevu: new Date('2025-02-20'),
    personnels: [personnels[0]._id, personnels[3]._id],
    fournitures: [fournitures[1]._id, fournitures[4]._id],
    outillages: [outils[1]._id, outils[7]._id],
    devis: [],
    adresse: '25 Rue de l’Opéra',
    code_postal: '75001',
    ville: 'Paris',
    localisation: { lon: 2.336, lat: 48.867 },
  },
  {
    numero: 'CH-403',
    title: 'Rénovation local de formation',
    description: 'Refonte du sol et des murs pour un centre de formation',
    notes: 'Utiliser des matériaux isolants phoniquement',
    commentaires: 'Prévision de travaux pour mars 2025',
    client: 'Centre de Formation Pro',
    status: 'À venir',
    debut_prevu: new Date('2025-03-01'),
    fin_prevu: new Date('2025-03-18'),
    personnels: [personnels[2]._id, personnels[8]._id],
    fournitures: [fournitures[2]._id, fournitures[5]._id],
    outillages: [outils[0]._id, outils[4]._id],
    devis: [],
    adresse: '47 Avenue du Savoir',
    code_postal: '75012',
    ville: 'Paris',
    localisation: { lon: 2.345, lat: 48.855 },
  },
  {
    numero: 'CH-404',
    title: 'Aménagement local commercial',
    description: 'Installation de revêtement carrelé et modernisation de l\'espace',
    notes: 'Prendre en compte la clientèle cible',
    commentaires: 'Projet à lancer en avril 2025',
    client: 'Boutique Chic',
    status: 'À venir',
    debut_prevu: new Date('2025-04-05'),
    fin_prevu: new Date('2025-04-20'),
    personnels: [personnels[5]._id, personnels[7]._id],
    fournitures: [fournitures[3]._id, fournitures[8]._id],
    outillages: [outils[2]._id, outils[6]._id],
    devis: [],
    adresse: '58 Rue de Rivoli',
    code_postal: '75004',
    ville: 'Paris',
    localisation: { lon: 2.352, lat: 48.857 },
  },
  {
    numero: 'CH-405',
    title: 'Préparation rénovation bureaux',
    description: 'Étude préliminaire et préparation du sol pour rénovation',
    notes: 'Vérifier l\'étanchéité et l\'isolation',
    commentaires: 'Programmation des travaux pour mai 2025',
    client: 'Groupe Entreprise',
    status: 'À venir',
    debut_prevu: new Date('2025-05-01'),
    fin_prevu: new Date('2025-05-15'),
    personnels: [personnels[6]._id, personnels[9]._id],
    fournitures: [fournitures[0]._id, fournitures[2]._id],
    outillages: [outils[3]._id, outils[8]._id],
    devis: [],
    adresse: '80 Boulevard des Entreprises',
    code_postal: '75017',
    ville: 'Paris',
    localisation: { lon: 2.359, lat: 48.862 },
  }
]);


    

    console.log('Données seed insérées avec succès.');
  } catch (err) {
    console.error('Erreur lors du seed :', err);
  } finally {
    mongoose.disconnect();
  }
}

seedDatabase();
